name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
