name: Static Analyse

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }} ~ 'static-analyse'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install modules
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
